### ISSUE TITLE
further implementation of input spectra formats

### ISSUE THREAD

**Issue by ciskakemper** [ICSM/ampere#10]
At the moment we have written a way to input the YAAAR FITS data format from CASSIS, but it would be nice to extend the capabilities of the code with:

- CASSIS IPAC Table (.tbl)
- CASSIS VO Table (directory with separate fits files for 6 orders for Lo-Res, including the two bonus orders)
- ISO SWS spectra from the ISO archive
....

**Comment by jontymarshall** [comment]
Closed as complete. If we want specific spectrum formats we should open an individual Issue for each.

**Comment by jontymarshall** [comment]
Closed as complete. If we want specific spectrum formats we should open an individual Issue for each.
