### ISSUE TITLE
Combine extinction models and flux models

### ISSUE THREAD

**Issue by pscicluna** [ICSM/ampere#16]
At present, only flux models are used. There should be an interface for these to be extinguished by (one of) the extinction model(s). We need to define a good interface to achieve this, probably by making it another component passed to the optimiser. Alternatively, we need a way to combine components from multiple model objects without writing entirely new classes for every combination.

**Comment by jontymarshall** [comment]
We've decided not to address extinction within ampere, so this issue is closed.
