### ISSUE TITLE
Add photometric covariances for known, well-calibrated instruments

### ISSUE THREAD

**Issue by pscicluna** [ICSM/ampere#20]
Gordon et al (2014) and Chastenet et al (2017) demonstrate a way of include the correlated component of calibration uncertainty for _Spitzer_ and _Herschel_ photometers. We should implement these covariance parameters where they are known. This includes building a library of known covariance properties and a means of appropriately associating this information with filters when they feature in an SED.

**Comment by pscicluna** [comment]
Change of strategy - instead of coding this ourselves, perhaps we should just provide an easier means for people to specify photometric covariances themselves?

**Comment by jontymarshall** [comment]
I support that response - if users have a specific case they want to investigate, it should be up to them to provide the relevant information.
