### ISSUE TITLE
How to define output wavelength grid for dusty

### ISSUE THREAD

**Issue by zazaho** [ICSM/ampere#25]
Currently the dusty model does not have an explicit way to specify the output wavelength grid. 
As far as I understand there is a file in the dusty/data directory called lambda_grid.dat which contains to output wavelengths. This table is made to satisfy several dusty internal criteria.

I have the impression that this table is combined with the wavelengths found in the optical properties tables to define the final output wavelengths. Physically this makes sense because sampling more finely than what is found in the inputs does not yield better models.

If we want to control the output wavelengths we will have to
1) patch the code to accept a filename.
2) write a file with our desired wavelengths that obeys the dusty rules.

**Comment by jontymarshall** [comment]
Closing this issue as no one currently uses Dusty - if anyone sees a use case for this, then we can reopen the issue.
