### ISSUE TITLE
Photometry(Data) data can not be inspected 

### ISSUE THREAD

**Issue by SaschaZeegers** [ICSM/ampere#32]
The data in Photometry cannot be inspected because of the repr returns: raise NotImplementedError(). I corrected it in my branch to return self.__str__(), but I am not sure if this is the best way. The absence of this bit of code caused my code to crash.

**Comment by ciskakemper** [comment]
To be implemented in master.

**Comment by pscicluna** [comment]
Need a better way to do this, I will try to come up with a good approach that is cleaner.

**Comment by jontymarshall** [comment]
We have implemented two ways to get the data out of a set using either data.__str__() or data.geef_data(). We should probably rename the geef_data() function to something more intuative to users, e.g. data.__data__()?
