### ISSUE TITLE
cov_mask not working as it should in data.py

### ISSUE THREAD

**Issue by ciskakemper** [ICSM/ampere#35]
Specifically in line 438, on branch ysosilfit, I had to remove cov_mask form that line to be able to read in the photometry. I was running pgQuasarSample.py from the examples directory.

**Comment by pscicluna** [comment]
I believe the updates in 3bc91c13ff35c10810b98d8fda63b1f790521d4c have fixed this, so I am closing this for now. 

The gist of the updates is that the masks are applied only to the 1D variables, and the covariance matrix is recomputed when a new mask is created so that it has the correct shape.
