### ISSUE TITLE
Utilities to sanitise/interpolate/extrapolate optical constants and/or opacities

### ISSUE THREAD

**Issue by pscicluna** [ICSM/ampere#43]
We could use some routines to take optical constants or opacities and modify them such that ampere models can use them effectively. This could include:
- Interpolation
- Extrapolation
- Continuum subtraction/division
- Smoothing
- Function-fitting

Or anything else people think is important. The idea here is to give some default treatment that is easily reported and either highly sensible in a single common case or minimises the non-sensibility averaged over all cases. However, we must include giant flashing lights and sirens so that the user knows it is happening and knows they should do it manually if they want something else.

**Comment by jontymarshall** [comment]
This is something that should be done by the user implementing other tools before using ampere.
