### ISSUE TITLE
Comparison with Verhoelst et al. (2009?) RSG sample

### ISSUE THREAD

**Issue by ciskakemper** [ICSM/ampere#47]
I don't remember the exact reference, but we had agreed that a comparison with the fit results with the Verhoelst et al. RSG sample would be very useful.

**Comment by jontymarshall** [comment]
https://ui.adsabs.harvard.edu/abs/2009A%26A...498..127V/abstract

**Comment by ciskakemper** [comment]
Not to be included in introductory paper
