### ISSUE TITLE
Ampere installation - pyphot not found

### ISSUE THREAD

**Issue by jontymarshall** [ICSM/ampere#48]
Running Mac OSX 11.4, fresh install of Anaconda and Ampere. I ran the setup.py script, which got almost all the necessary modules except PyPhot with error: 

"No local packages or working download links found for pyphot
error: Could not find suitable distribution for Requirement.parse('pyphot')"

However, copying and pasting the "> pip install <GitLink>" for PyPhot (as suggested on their webpage) worked fine on the command line. Perhaps we should implement that in the setup script?

**Comment by pscicluna** [comment]
With the changes to Photometry, our fork of pyphot is no longer required. Setup.py (and, by extension, pip install .) should now work as intended.
