### ISSUE TITLE
Ampere not copying directories across to anaconda path during setup

### ISSUE THREAD

**Issue by jontymarshall** [ICSM/ampere#49]
Running Mac OSX 11.4, fresh install of Anaconda and Ampere. Ran the setup.py script to install ampere - it copies the files from the ampere module into the Anaconda installation path but not the directories (Opacties, utils, Testdata). This prevents the example scripts working straight off the bat. Not sure if this is a bug or a feature, as maybe the user is meant to specify their own directory/location.

**Comment by pscicluna** [comment]
I think this should be considered a feature. The code should be improved so that the user specifies a directory to look for opacities in. utils needs to be added to the import structure of ampere, however.
