### ISSUE TITLE
extractPhotometry() unexpected keyword "Fnu" in data.py line 407

### ISSUE THREAD

**Issue by jontymarshall** [ICSM/ampere#50]
Ampere example wouldn't run due to unexpected keyword in PyPhot calling extractPhotometry() with Fnu=True specified. I commented out the keyword from the function call and it ran just fine.

**Comment by pscicluna** [comment]
Recent updates to Photometry should fix this. Please double check it and close the issue.

**Comment by pscicluna** [comment]
No issues reported, closing.
