### ISSUE TITLE
Wrong dimensions for array 'spec' in helpers.py line 62

### ISSUE THREAD

**Issue by jontymarshall** [ICSM/ampere#51]
Running the powerlaw AGN example script and come across an error when setting up the optimiser. The problem occurs with a variable spec. In Line 62 of helpers.py it's defined as 
> s0 = spec[:,xl]
but spec is one dimensional (for this example script at least). I deleted the ':,' part (as all the other variables in that function were defined with index 'xl' and the code runs fine.

**Comment by pscicluna** [comment]
Closing unless further issues reported.
