### ISSUE TITLE
progress bars

### ISSUE THREAD

**Issue by SaschaZeegers** [ICSM/ampere#52]
Not so much an issue, but an idea to add a feature to the code. 
It would be nice if Ampere could show how far in the process it is by adding a progress bar. Then you can get an estimate of the time it needs to run.

**Comment by pscicluna** [comment]
Added for emcee in https://github.com/ICSM/ampere/commit/3a7359bda74b696f9980b6ed6e310152f8e7c3f8 but this will only work if your installation of emcee is sufficiently up to date (I don't remember exactly which version added this keyword). Please test it and see if it works. 

I will keep the issue open as a reminder to add equivalent functionality to other samplers whenever adding them.
