### ISSUE TITLE
Merge NGC6302 branch into main branch

### ISSUE THREAD

**Issue by ciskakemper** [ICSM/ampere#66]

**Comment by ciskakemper** [comment]
Hi @pscicluna, maybe you can wait a little with doing this: I just discovered that I missed a dust component that I used in 2002, so I am going to adapt and re-run my example. I will let you know when it is finished.

**Comment by ciskakemper** [comment]
Hi @pscicluna. I am now fully done with the NGC 6302 example. You can merge it into the master branch. 

Happy new year!

**Comment by ciskakemper** [comment]
Reminder for @pscicluna : you can merge the ngc6302 branch into the master branch now. I am all done.

**Comment by pscicluna** [comment]
https://github.com/ICSM/ampere/pull/69/

**Comment by ciskakemper** [comment]
I was not aware that I needed to confirm pull request #69 , so I was happily waiting. But today I found the confirm button and clicked it, so now the branch is merged into mater.
